### ISSUE TITLE
docker版本加入http-proxy参数后脚本运行失败

### ISSUE THREAD

**Issue by Zayia** [xream/http-meta#2]
宿主机无科学上网环境
于是在substore容器内加入了http-proxy参数来实现容器科学上网环境
经测试，未加入参数的时候各种测速，测活的脚本都可以运行
但是加入参数后，运行脚本提示如下
[sub-store] ERROR: Cannot apply operator Script Operator(function operator)! Reason: POST URL: http://127.0.0.1:9876/start exceeds the timeout 1000 ms

**Comment by xream** [comment]
供参考: 

<img width="532" alt="Image" src="https://github.com/user-attachments/assets/792f2d56-4f62-40e7-9b91-81a962bb6b96" />

**Comment by Zayia** [comment]
最终这样解决了
在容器内加入端口映射，将容器内的9876映射到局域网中的9876
然后使用局域网IP：9876实现脚本的控制

**Comment by Zayia** [comment]
如果设置端口转发的话，一些需要使用其他端口来运行的脚本依然无法运行
还是只能使用host模式

**Comment by xream** [comment]
嗯 host 模式也挺好的. 现在各方面安全性都足够了. 类似这样:
```
environment:
      SUB_STORE_BACKEND_API_PORT: 3001
      SUB_STORE_BACKEND_MERGE: true
      SUB_STORE_FRONTEND_BACKEND_PATH: /xxxxxxxxxxxxxxxxxx
      PORT: 9876
      HOST: "::"
      AUTHORIZATION: "yyyyyyyy"
```
